- name: copy logstash configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: check logstash is started is started or not
  ansible.builtin.shell: sleep 60; netstat -lntp | grep 5044
