- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Enable and Install nodejs
  ansible.builtin.dnf:
    name: "@nodejs:18.19.0"
    state: installed







