- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Install the latest version of nodejs
  ansible.builtin.dnf:
    name: "nodejs:18.18.1"
    state: installed






