- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent
    disable_gpg_check: yes

- name: Install nodejs >= 18
  ansible.builtin.dnf:
    name: nodejs >= 18
    state: installed



