- name: Disable nodejs
  ansible.builtin.shell: dnf module disable nodejs

- name: Enable nodejs version 18
  ansible.builtin.shell: dnf module enable nodejs:18

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install nodejs dependencies
  community.general.npm:
    path: /app

- name: Schema setup
  ansible.builtin.import_tasks:
    file: schema-setup.yml






