- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Install nodejs >=18.19.0
  ansible.builtin.dnf:
    name: nodejs >= 18.19.0
    state: installed






