- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Install node.js package on version 1.6.1.
  community.general.npm:
    name: node.js
    version: '18.19.0'
    state: installed






