- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent
    disable_gpg_check: yes

- name: Install node.js
  ansible.builtin.dnf:
    name: node
    version: ">=18"
    state: installed



