- name: Configure nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_1ts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed





