- name: Remove the nodejs package
  ansible.builtin.dnf:
    name: nodejs
    state: absent
    disable_gpg_check: yes

- name: Install nodejs
  ansible.builtin.dnf:
    name: "nodejs - v18.18.1"
    state: installed



