- name: Remove the Node.js
  ansible.builtin.dnf:
    name: "nodejs"
    state: absent


- name:  Enable and Install nodejs version 18
  ansible.builtin.dnf:
    name: "nodejs:18"
    state: installed

- name: App pre-requisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install Nodejs dependencies
  community.general.npm:
    path: /app

- name: Schema set-up
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: Systemd set-up
  ansible.builtin.import_tasks:
    file: systemd-setup.yml



