{
 "title": "RoboShop",
 "time": { "from": "2024-01-27T06:13:28.788Z", "to": "2024-01-27T06:17:14.310Z" },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"cart.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"catalogue.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"payment.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"shipping.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"user.service\", state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory%",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - (((node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server UP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{name}}" }
   ]
  }
 ]
}